CONTAINER oflock
{
	NAME oflock;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		DEFAULT 0;

		REAL OFLOCK_WEIGHT { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
	}

	GROUP OFLOCK_TAB_1
	{
		DEFAULT 1;

		REAL OFLOCK_SIGHT { UNIT METER; MIN 0.0; STEP 0.1; }

		SEPARATOR OFLOCK_CENTER   {  }
		REAL OFLOCK_CENTER_WEIGHT { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }

		SEPARATOR OFLOCK_NEIGHBORDIST   {  }
		REAL OFLOCK_NEIGHBORDIST_WEIGHT { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		REAL OFLOCK_NEIGHBORDIST_DIST   { UNIT METER; MIN 0.0; STEP 0.1; }

		SEPARATOR OFLOCK_MATCHVEL   {  }
		REAL OFLOCK_MATCHVEL_WEIGHT { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }

		SEPARATOR OFLOCK_LEVELFLIGHT   {  }
		REAL OFLOCK_LEVELFLIGHT_WEIGHT { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }

		SEPARATOR OFLOCK_TURBULENCE      {  }
		REAL OFLOCK_TURBULENCE_WEIGHT    { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		REAL OFLOCK_TURBULENCE_FREQUENCY { UNIT REAL; STEP 0.1; }
		REAL OFLOCK_TURBULENCE_SCALE     { UNIT REAL; STEP 0.1; }
	}

	GROUP OFLOCK_TAB_2
	{
		SEPARATOR OFLOCK_SPEED   {  }
		REAL OFLOCK_SPEED_WEIGHT { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		LONG OFLOCK_SPEED_MODE   { CYCLE { OFLOCK_SPEED_MODE_SOFT; OFLOCK_SPEED_MODE_HARD; } }
		REAL OFLOCK_SPEED_MIN    { UNIT METER; MIN 0.0; }
		REAL OFLOCK_SPEED_MAX    { UNIT METER; MIN 0.0; }

		SEPARATOR OFLOCK_TARGET       {  }
		REAL OFLOCK_TARGET_WEIGHT     { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		IN_EXCLUDE OFLOCK_TARGET_LINK { ACCEPT { 1029185; } }

		SEPARATOR OFLOCK_REPELL       {  }
		REAL OFLOCK_REPELL_WEIGHT     { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		IN_EXCLUDE OFLOCK_REPELL_LINK { ACCEPT { 1029184; } }

		SEPARATOR OFLOCK_AVOIDGEO   {  }
		REAL OFLOCK_AVOIDGEO_WEIGHT { UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		REAL OFLOCK_AVOIDGEO_DIST   { UNIT METER; MIN 0.0; STEP 0.1; }
		LONG OFLOCK_AVOIDGEO_MODE   { CYCLE { OFLOCK_AVOIDGEO_MODE_SOFT; OFLOCK_AVOIDGEO_MODE_HARD; } }
		LINK OFLOCK_AVOIDGEO_LINK   { ACCEPT { Opolygon; } }
	}
}
