CONTAINER Oflocktarget
{
	NAME Oflocktarget;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		BOOL OFLOCKTARGET_ENABLED					{  }
		REAL OFLOCKTARGET_WEIGHT					{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		REAL OFLOCKTARGET_RADIUS					{ UNIT METER; MIN 0.0; STEP 0.1; }
		BOOL OFLOCKTARGET_RADIUS_INFINITE {  }
	}
}
