#ifndef OFLOCKTARGET_H__
#define OFLOCKTARGET_H__

enum
{
	OFLOCKTARGET_WEIGHT						= 10000,
	OFLOCKTARGET_RADIUS						= 10001,
	OFLOCKTARGET_ENABLED					= 10002,
	OFLOCKTARGET_RADIUS_INFINITE	= 10003
};

#endif
