CONTAINER Oflockrepeller
{
	NAME Oflockrepeller;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		BOOL OFLOCKREPELLER_ENABLED				{  }
		REAL OFLOCKREPELLER_WEIGHT				{ UNIT PERCENT; MIN 0.0; MAX 100.0; CUSTOMGUI REALSLIDER; }
		REAL OFLOCKREPELLER_RADIUS				{ UNIT METER; MIN 0.0; STEP 0.1; }
	}
}
